### PR TITLE
Fixed scanning on Samsung Grand Prime

### PR DESCRIPTION
**Pull request by gczudowski**
https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/392#issuecomment-287672090

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi!

Interesting PR. Did scanning not work at all, or did you see other symptoms?

**Comment by gczudowski** [comment]
Hello!

The issue was the phone chose the minimum resolution possible, therefore the quality of the image was too poor to enable scanning. Below you can see that the screen in portrait was 540x960, the phone supported 960x540 but it didn't choose it as it didn't take into account if screen resolution and camera resolution are of the same orientation. The issue was present on all phones, but on most phones the default resolution is really high (e.g. 1920, 1080) .This particular phone's default resolution was `144x176`. Logs below:

```
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: Display at: 0
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: Camera at: 90
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: Final display orientation: 90
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: Clockwise rotation from display to camera: 90
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: Screen resolution in current orientation: Point(540, 960)
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: Supported preview sizes: 1280x960 1280x720 960x540 720x540 800x480 720x480 640x480 640x360 352x288 320x240 176x144 
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: No suitable preview sizes, using default: Point(176, 144)
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: Camera resolution: Point(176, 144)
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: Supported preview sizes: 1280x960 1280x720 960x540 720x540 800x480 720x480 640x480 640x360 352x288 320x240 176x144 
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: No suitable preview sizes, using default: Point(176, 144)
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: Best available preview size: Point(176, 144)
03-27 11:10:07.062 11143-11143/com.app I/CameraConfiguration: Preview size on screen: Point(144, 176)
```

**Comment by EddyVerbruggen** [comment]
Let me merge this and run some tests, I'll let you know how it goes. Thanks for now! 👍

**Comment by EddyVerbruggen** [comment]
I don't have a device that was problematic, so can only confirm this still works fine with my non-Samsung devices.

Thanks for contributing!

**Pull request merged**
